repos:
- hooks:
    - id: commitizen
      stages: [ commit-msg ]
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.23.0
- repo: local
  hooks:
  - id: pdm-checks
    name: Run PDM checks
    entry: pdm run checks
    language: system
    always_run: true
    pass_filenames: false
